name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # =========================
      # 🌍 3D CONTRIBUTION GRAPH
      # =========================
      - name: Generate 3D Profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          username: ShaktiKourav
          output: dist/profile-3d.svg

      # =========================
      # 🚀 PUSH TO OUTPUT BRANCH
      # =========================
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output