
name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 */12 * * *"   # Every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  wakatime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          SHOW_TITLE: true
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          BLOCKS: █
          LANG_COUNT: 8
          STOP_AT_OTHER: false

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md

          git diff --cached --quiet || git commit -m "Update WakaTime Stats"

          git push

